### ISSUE TITLE
Calibredb communication failed

### ISSUE THREAD

**Issue by yongbi85** [linuxserver/docker-lazylibrarian#37] opened 2019-08-14 15:41 UTC
DSM 6.1.7

Was using aptalca thraxis lazylibrarian docker image until today. Ll is up to date but the os image hasn’t been updated in a long time so decided to switch over to yours

Calibredb was working fine on the other image but with yours i get the following error :

calibredb communication failed: Traceback (most recent call last):
  File "site.py", line 75, in main
  File "site-packages/calibre/db/cli/main.py", line 14, in 
  File "site-packages/calibre/db/legacy.py", line 17, in 
  File "site-packages/calibre/db/backend.py", line 35, in 
  File "site-packages/calibre/utils/img.py", line 18, in 
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

I even forced amd64-latest in case but to no avail

**Comment by CHBMB** [comment] 2019-08-14 18:40
Using the Calibre binary is no longer the recommended way to use LL as far as I can tell from the docs.  However that being said, if you let me know exactly how you've configured things so I can try and reproduce I'll take a look.

At the moment I'm not able to reproduce

**Comment by yongbi85** [comment] 2019-08-14 19:48
Ok so no port as im using another docker as net container for openvpn (libgen is blocked in my country)
Volume bind : 
/downloads
/ebooks
/config

PUID and PGID set to an user owner of those directories and is the same as the calibre aptalca docker

DOCKER_MODS set of course
/usr/bin/calibredb as path to calibredb

The only difference i see is that thraxis lazylibrarian docker put the calibre config folder as an environment variable and i see the .py files in the /config folder

As for why im using calibredb is because with autoadd it forces me to have twice all my books... in one folder for lazylibrarian and a folder for calibre...

**Comment by thelamer** [comment] 2019-08-19 00:05
Are you absolutely sure you pulled the latest verison of this image ? The error you posted indicates that it is missing a lib and cannot run the calibredb binary, but this image runs it just fine: 
```
root@c8508dbdb9e8:/# ldd /usr/bin/calibredb 
	linux-vdso.so.1 (0x00007ffcad758000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0864ca8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0865099000)
root@c8508dbdb9e8:/# calibredb 
Usage: calibredb command [options] [arguments]

calibredb is the command line interface to the calibre books database.
```
This is from inside a lazylibrarian docker container with the mod flag set.

**Comment by thelamer** [comment] 2019-08-25 23:34
Closing pending a response so I don't forget

**Closed as completed by thelamer** 2019-08-25 23:34 UTC
